### ISSUE TITLE
Does Google find my blog on the internet?

### ISSUE THREAD

**Issue by huyng12** [thien-do/memos-pub#2]
I have some questions:

- Does Google find my blog on the internet?
- Can I add Google Tag Manager / Google Analytics to my blog?
- Can I add sitemap to my blog?

**Comment by thien-do** [comment]
> Does Google find my blog on the internet?

Possibly. At the moment we don't actively register it in any way, but technically if the link to your blog is somewhere reachable publicly (e.g. someone else share a link to huyng12.memos.pub on their public website) then your blog is indexed by Google and other search engines. This is to the best of my knowledge.

> Can I add Google Tag Manager / Google Analytics to my blog?

At the moment, not yet. However we are looking into an optional `memos.pub.json` at the root of your repo which should let you have such functionality.

> Can I add sitemap to my blog?

Not yet. This is also something we'd like to have but not figured out what should be the behavior/configuration for the blog author yet.

I'll keep you updated via this issue if you don't mind

**Comment by huyng12** [comment]
Yep, thank you so much.

**Comment by thien-do** [comment]
@huyng12 update :D for

> Can I add Google Tag Manager / Google Analytics to my blog?

we will cover that in #18 

personally I'd say to try some analytic solution without tracking.. or at least best option for privacy
