### ISSUE TITLE
Support sharing preview

### ISSUE THREAD

**Issue by ZeroX-DG** [thien-do/memos-pub#4]
Current we don't have sharing preview when the post is being shared on social media and that's not fun. :cry:

**Comment by thien-do** [comment]
https://unifiedjs.com/explore/package/rehype-infer-description-meta/

**Comment by huytd** [comment]
@ZeroX-DG by sharing view, did you mean the [Open Graph Metadata](https://ogp.me)?

It's a missing feature, so I think we should consider this as a bug.

**Comment by ZeroX-DG** [comment]
Yep that's exactly what I mean.

**Comment by thien-do** [comment]
We have title and description infer now :D https://github.com/thien-do/memos-pub/commit/ec22bee3bb9ad832b39026d67e20222a63cb32ce

Please feel free to open another issue if you want something else in preview (date, image?)
