### ISSUE TITLE
Render folder with README.md as content page

### ISSUE THREAD

**Issue by huytd** [thien-do/memos-pub#8]
Currently, memos-pub show every file in a folder. This led to a situation where the folder only has 1 markdown file, for example, `README.md`, we still list that file. 

```
notes
└ post-001
  └ README.md
```

For example https://ledongthuc.memos.pub/notes/leetcode/binary-search-tree-iterator

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/613943/157497524-0e24cdef-833c-43c0-90c5-454a506d1e52.png">

A good way to go about this situation is using Github's default behavior, always render the content of `README.md` file in a folder. There will be a case where the user want to navigate into subfolders, in this case we can skip the render.

So, to summarize, I think we should adopt a render behavior as follow:

- If a folder has nothing but a `README.md` file, we can just render that file out.

  ```
  notes
  └ post-001
    └ README.md

  URL: /notes/post-001 -> Render the README.md
  URL: /notes/post-001/README.md -> Also render the README.md
  ```

- If the folder does not have any markdown file, render the folder as a list

  ```
  notes
  └ post-001
    └ a-sub-folder

  URL: /notes/post-001 -> Render the folder list
  URL: /notes/post-001/a-sub-folder -> Render empty list
  ```

  The empty folder case can be handled in #6 

- If the folder contains both `README.md` file and other files/folders, render the folder as a list

  ```
  notes
  └ post-001
    └ README.md
    └ other.md
    └ subfolder
      └ README.md

  URL: /notes/post-001 -> Render the folder as a list
  URL: /notes/post-001/README.md -> Render the README.md
  URL: /notes/post-001/subfolder -> Render the subfolder/README.md 
  ```

- **(Nice to have)** If the folder contains both `README.md` file and other files, but none of them are markdown file, we should consider rendering the README.md file as default:

  ```
  notes
  └ post-001
    └ README.md
    └ img.png
    └ virus.exe

  URL: /notes/post-001 -> Render the README.md 
  ```

**Comment by thien-do** [comment]
This is great. Also I see some blogs that have a folder with `index.md` or `index.mdx`. Should treat them as folder's markdown too I think

**Comment by thien-do** [comment]
Done with b1a173b757c3a39f4eef679859891c452ebe2934 and 7fbf67ec3d024de1223d5ced6ef5bdfd94966dbd
